image: ubuntu:16.04

variables:
  GIT_SUBMODULE_STRATEGY: recursive

  DEVKITPRO: "/opt/devkitpro"
  DEVKITPPC: "/opt/devkitpro/devkitPPC"
  WUT_ROOT: "/opt/devkitpro/wut"

.common: &common
  script:
    - PLATFORM=$PLATFORM ./dependency_helper.sh
    - make -f Makefile.$PLATFORM
  artifacts:
    paths:
      - appstore-$CI_COMMIT_TAG.$EXT

PC:
  <<: *common
  variables:
    PLATFORM=pc
    EXT=bin

WiiU:
  <<: *common
  variables:
    PLATFORM=wiiu
    EXT=rpx

Switch:
  <<: *common
  variables:
    PLATFORM=switch
    EXT=nro
