image: ubuntu:16.04

variables:
  GIT_SUBMODULE_STRATEGY: recursive

  DEVKITPRO: "/opt/devkitpro"
  DEVKITPPC: "/opt/devkitpro/devkitPPC"
  WUT_ROOT: "/opt/devkitpro/wut"

Build:
  stage: build
  script:
    - apt-get update && apt-get -y install sudo

    - PLATFORM=pc ./dependency_helper.sh
    - make -f Makefile.pc

    - PLATFORM=wiiu ./dependency_helper.sh
    - make -f Makefile.wiiu

    - PLATFORM=switch ./dependency_helper.sh
    - make -f Makefile.switch

  artifacts:
    paths:
      - appstore.bin
      - appstore.rpx
      - appstore.nro

  only:
    - master
